src/components/banner.tsx
src/components/ui/list-header.tsx
src/pages/index.tsx

will be used for issues and pull requests

new list heading component

---

README.md
documentation/development/contributing.md

Resolves #34 
Let's use function components instead of arrow functions.

Update coding conventions.

---

src/app/[entity]/[repo]/page.tsx
src/app/layout.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/list-header.tsx

Add a mobile layout and work as mobile first.
Meaning we have to think and write for a mobile view first and then others devices.
Example: `<div className="grid grid-cols-4 gap-6 lg:grid-cols-2">`
Steps :
- Fix global grid on mobile
- Fix aside width
- Convert `Tabs` to `Link`
Check if elements fit in mobile

Add mobile layout first step

---

src/app/[entity]/[repo]/page.tsx

Fix top divider

---

documentation/development/contributing.md

Add documentation with some tools

Add tooling documentation

---

src/components/ui/header.tsx

Add array mapping for dropdown menu contents

---

documentation/development/contributing.md
documentation/pull_request_template.md

Add default pull request template like this:

Add default pull request template

---

.prettierrc
package.json
yarn.lock

Add `prettier-plugin-tailwindcss` to sort `tailwind` classes

Add prettier-plugin-tailwindcss

---

src/app/[entity]/[repo]/layout.tsx
src/components/main-nav.tsx
src/components/ui/header.tsx

`src/components/ui/header.tsx` added some hover animations to the mainnav
`src/app/[entity]/[repo]/layout.tsx` added underline hover animation to name / project

Added hover animations for header (MainNav), logo, and NAME / PROJECT

---

src/app/[entity]/[repo]/layout.tsx

Improve desktop, tablet and mobile layout for the top section

Improve top banner layout on tablet and mobile

---

documentation/nostr/NIPs.md

👉🏻 &nbsp; Link @melvincarvalho 's NIP-17 draft to NIPs.md
👉🏻 &nbsp; N/A

Link NIP-17 draft to NIPs.md

---

.eslintrc.cjs
src/app/[entity]/[repo]/page.tsx
src/components/ui/header.tsx

fixed linter

---

public/.well-known/nostr.json

👉🏻 &nbsp; added nip5 for the nostr account (https://no.str.bio/nostrgit) and for core contributors
Feel free to suggest your own NIP-5 identifiers in this PR with the suggest feature of github

added nip-5

---

public/.well-known/nostr.json

👉🏻 &nbsp; Wasn't fast enough to react to #88 and decided I want a lowercase name :smile: 
👉🏻 &nbsp; N/A

Update own name in .well_known

---

src/components/ui/button.tsx

fixed button focus

---

public/.well-known/nostr.json

👉🏻 &nbsp; Add a name to nostrgit nostr user in .well_known. Leave the "_@nostrgit.com" row for reference.
👉🏻 &nbsp; N/A

NIP-5 nostrgit user

---

documentation/development/contributing.md

👉🏻 &nbsp; Closes #97. Add a strong recommendation to attach screenshots or loom.com videos to PRs to make code reviews smoother. 
👉🏻 &nbsp; N/A

Screenshots or loom videos to PRs

---

README.md

that way I can invite more people to the vercel team account for logs without eating all of the costs
https://vercel.com/guides/can-vercel-sponsor-my-open-source-project

applying for vercel sponsorship

---

documentation/development/contributing.md

👉🏻 &nbsp; Added 'Troubleshooting Vercel' section to contributing.md. Instruction to see the relevant error message with 'yarn build'.
👉🏻 &nbsp; N/A

Troubleshooting Vercel

---

documentation/development/contributing.md

👉🏻 &nbsp; Encourage using Lucide icon components in contributing.md
👉🏻 &nbsp; N/A

Lucide icon components in contributing.md

---

README.md

👉🏻 &nbsp; There was still a mention to open a new Discussion for any questions in the readme. Edited to issues.
👉🏻 &nbsp; N/A

Update readme about using issues not discussions

---

src/app/layout.tsx
src/app/login/page.tsx
src/components/ui/header.tsx

- Fix issue with avatar size
before:
after:
- Remove min-width on main layout
- Fix dropdown signin
👉🏻 Check if Avatar and layout are not broken anymore
related to https://github.com/NostrGit/NostrGit/issues/141

Fix responsive layout and Avatar UI

---

README.md

👉🏻 &nbsp; Update the Contibuting section of readme with a link to bitcoin-development docs, which contain useful information about contributing to the Bitcoin open-source ecosystem in general. Good principles over there.
👉🏻 &nbsp; N/A

Update readme with link to bitcoin-development docs

---

src/app/pulls/page.tsx
src/components/ui/header.tsx

👉🏻 &nbsp;Please add a description of what this `pull request` does.
This PR adds a basic UI for the `/pulls` page #154 
👉🏻 &nbsp;Please add what you think the reviewer has to test.

feat: basic  /pulls page ui

---

pull_request_template.md

- use yarn build to see errors locally
- turned text into comments
none

improved pull request template

---

src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx

👉🏻 &nbsp;Please add a description of what this `pull request` does.
This is a basic UI for the `[entity]/[repo]/issues` page closes #156 
👉🏻 &nbsp;Please add what you think the reviewer has to test.

feat:ui for [entity]/[repo]/issues page

---

src/app/[entity]/[repo]/pulls/new/page.tsx
src/app/[entity]/[repo]/pulls/page.tsx

adds a basic page for `/[entity]/[repo]/pulls`  closes #15 

feat: [entity]/[repo]/pulls page

---

src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx
src/app/[entity]/[repo]/layout.tsx
src/app/[entity]/[repo]/page.tsx
src/app/login/page.tsx
src/components/logo.tsx
src/components/main-nav.tsx
src/components/mobile-nav.tsx
src/components/search-bar.tsx
src/components/ui/header.tsx

- fixed a ton of padding and sizing
- new `<SearchBar>`
- new `<Logo>`
- added Logo to mobile heading
- added notification icon

frontend improvements

---

src/app/[entity]/[repo]/issues/new/page.tsx
src/components/mobile-nav.tsx
src/components/ui/header.tsx
src/components/ui/textarea.tsx

Adds a starting point UI for adding new issues.
Uses mockLabels as data.
User must be logged in with a private key to post issues.
The filtering of labels doesn't work yet, but they can be checked:
Nothing should break by interacting with the page.

Page for creating a new issue /[entity]/[repo]/issues/new/

---

package.json
src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx
src/app/[entity]/[repo]/layout.tsx
src/app/[entity]/[repo]/pulls/page.tsx
src/components/filter-bar.tsx
tailwind.config.cjs
yarn.lock

- made navigatio scrollable on mobile
- added tailwind-scrollbar
- fixed some layout issues on /issue and /pull
https://user-images.githubusercontent.com/8019099/224558320-cedfccd5-e0e9-4850-b1d5-701fa4bd9594.mp4

make navigation slideable on mobile and fixed some layout issues

---

documentation/development/contributing.md
src/app/issues/page.tsx
src/app/pulls/page.tsx

clean up css on /issues and /pulls pages

---

public/safari-pinned-tab.svg
src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx
src/app/[entity]/[repo]/pulls/page.tsx
src/app/issues/page.tsx
src/app/pulls/page.tsx
src/app/settings/layout.tsx
src/components/filter-bar.tsx
src/components/ui/avatar.tsx
src/components/ui/badge.tsx
src/components/ui/button.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/input.tsx
src/components/ui/list-header.tsx
src/components/ui/tabs.tsx
src/components/ui/textarea.tsx

UI: slate replaced with zinc

---

package.json
src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx
src/app/[entity]/[repo]/layout.tsx
src/app/[entity]/[repo]/page.tsx
src/app/[entity]/[repo]/pulls/page.tsx
src/app/issues/page.tsx
src/app/login/page.tsx
src/app/pulls/page.tsx
src/app/settings/account/page.tsx
src/app/settings/appearance/page.tsx
src/app/settings/layout.tsx
src/app/settings/notifications/page.tsx
src/app/settings/page.tsx
src/app/settings/profile/page.tsx
src/app/settings/relays/page.tsx
src/components/filter-bar.tsx
src/components/settings-hero.tsx
src/components/ui/dropdown-menu.tsx
src/components/ui/header.tsx
src/components/ui/label.tsx
src/components/ui/textarea.tsx
tailwind.config.cjs
yarn.lock

/settings UI

---

src/app/layout.tsx
src/lib/hooks/useIsMounted.tsx

This closes #181
This adds an extra hook `useIsMounted` which is a conditional to show the contents inside the `<NostrProvider />` on the `RootLayout`.   Let me know if you see anything wrong with this method.

181 fix hydration errors

---

package.json
src/app/settings/profile/page.tsx
yarn.lock

adds react-hook-forms package
`useForm` added to `/settings/profile` page
closes #187 

187-feat:react-hook-forms

---

src/app/login/page.tsx
src/components/ui/header.tsx

Add a redirect to the profile page when user clicks on 
Also clean `console.log()`
https://github.com/NostrGit/NostrGit/issues/149
Test if redirect works

Add a redirect to profile page when clicking on your account name

---

src/components/logo.tsx

193 fix logo

---

documentation/development/contributing.md

Closes #167.
Tailwindui was already mentioned, but I included the rest of the issue in the contributing.md as well.
Added some subheadings.
N/A

Tailwindui to contributing.md

---

src/components/ui/header.tsx

cleans up on click menu navigation by moving `<Link />` outside of the `<DropdownMenuItem  />`
closes #197 

197-header-navigation

---

src/app/[entity]/[repo]/issues/new/page.tsx
src/app/[entity]/[repo]/issues/page.tsx
src/app/[entity]/[repo]/pulls/page.tsx
src/app/signup/page.tsx
src/components/ui/header.tsx

Closes #195 and #196.
- UI for /signup
- nostr profile creation
- logs in the created user with their **pubkey**

/signup UI & functionality

---

src/app/[entity]/[repo]/issues/new/page.tsx

Fixes [#164](https://github.com/NostrGit/NostrGit/issues/164)
- Smooth filtering of labels when creating a new issue
https://www.loom.com/share/bd1f193f08c44ce1a408c93fc1cbdcf1

Label filtering in new issue page

---

src/app/signup/page.tsx
src/components/mobile-nav.tsx
src/components/ui/header.tsx

mobile nav improvements
